"""empty message

Revision ID: 226bf3364fbb
Revises: 
Create Date: 2019-09-24 15:16:38.641781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226bf3364fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用户主键'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('mobile', sa.String(length=11), nullable=False, comment='手机号'),
    sa.Column('email', sa.String(length=100), server_default='', nullable=True),
    sa.Column('sex', sa.Integer(), nullable=False, comment='性别(1：男 2：女 0：没填写)'),
    sa.Column('avatar', sa.String(length=50), nullable=False, comment='头像'),
    sa.Column('login_name', sa.String(length=20), nullable=False, comment='登录名'),
    sa.Column('login_pwd', sa.String(length=32), nullable=False, comment='登陆密码'),
    sa.Column('login_salt', sa.String(length=32), nullable=False, comment='加密盐'),
    sa.Column('status', sa.Integer(), nullable=False, comment='账号状态(1：已删除  0：正常)'),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.Column('insert_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_name'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
